### ISSUE TITLE
Certificates for https://sparse.tamu.edu/ expired?

### ISSUE THREAD

**Issue by willow-ahrens** [JuliaMatrices/MatrixDepot.jl#100]
Is anyone else getting curl errors like this?

An example from loading MatrixDepot.
```
┌ Warning: exception during initialization: 'ProcessFailedException(Base.Process[Process(`sh -c 'curl "https://sparse.tamu.edu/files/ss_index.mat" -Lso "/home/runner/.julia/scratchspaces/b51810bb-c9f3-55da-ae3c-350fc1fbce05/data/ss_index.mat"'`, ProcessExited(60))])'
```

This is due to expired certificates from the suitesparse website. A browser might experience similar issues.

A quick fix is to put `-k` right after `curl` in the `download_command()` function, but I'm not sure if that's safe because it essentially says to ignore the certificates. Any ideas on how we can fix this one?

**Comment by KlausC** [comment]
Actually the sparse.tamu.edu certificate is now valid since 2022-08-11 up to 2023-08-11.

I don't think it is worth while trying the insecure mode in case the secure mode fails.

**Comment by willow-ahrens** [comment]
Yep, I think it works now. For anyone who runs into this in the future, my fix was
```
MatrixDepot.downloadcommand(url::AbstractString, filename::AbstractString="-") =
    `sh -c 'curl -k "'$url'" -Lso "'$filename'"'
```
