### ISSUE TITLE
Symmetric matrices

### ISSUE THREAD

**Issue by dpo** [JuliaMatrices/MatrixDepot.jl#26]
It's probably not a good idea to declare symmetric matrices as `Symmetric{...}` for the time being because it seems sparsity is then ignored. See https://discourse.julialang.org/t/slow-matrix-vector-product-with-symmetric-matrices/3968 for some timings and [an explanation](https://discourse.julialang.org/t/slow-matrix-vector-product-with-symmetric-matrices/3968/6?u=dpo).

**Comment by KlausC** [comment]
Matrices of type `Symmetric{Real,SparseMatrixCSC}` have now support for fast operations.
If that is not enough, you can transform to a pure sparse matrix using `sparse`.
