### ISSUE TITLE
Search UFL Collection

### ISSUE THREAD

**Issue by dpo** [JuliaMatrices/MatrixDepot.jl#29]
I didn't find a way to filter through the UFL collection with this package. I put together a makeshift solution that others might find useful or improve upon. I downloaded the data file used by the web interface at http://yifanhu.net/GALLERY/GRAPHS/search.html and converted it to something that resembles a CSV file. Then, JuliaDB lets users filter matrices that have certain properties.

In case it's useful, the files are here:

https://gist.github.com/99ec73923425a82d6f07beee3ab63cde

I hope something like that can be added to this repository in the future.

**Comment by KlausC** [comment]
Most of the search features mentioned in this issue, including keyword search, are contained in PR 31.

**Comment by KlausC** [comment]
resolved in v1.0
