### ISSUE TITLE
Error occurs in "download.jl" on Windows cause of "tar" function

### ISSUE THREAD

**Issue by BursonTang** [JuliaMatrices/MatrixDepot.jl#47]
Hello, I got an error when trying to download data using:
`mdopen("SNAP/web-Google")`
Error Message:  tar: Cannot connect to C: resolve failed
failed process: Process(`tar -vxf 'C:\path\path' -C 'C:\path\path' ....)

According to tar manual at chapter 6.1 Choosing and Naming Archive Files, "If the archive file name includes a colon (‘:’), then it is assumed to be a file on another machine" and also ". Filenames with a colon are common for Windows users (e.g., C: ) and if you need to use a file whose name includes a colon, then the remote tape drive behavior can be inhibited by using the ‘--force-local’ option".

The problem is solved by editing the download.jl line199 to run(`tar --force-local -vxf $tarfile -C $dir`). Maybe you should modify this line of code. 

Thank you.

**Comment by KlausC** [comment]
resolved in v1.0
