### ISSUE TITLE
Classification and regression

### ISSUE THREAD

**Issue by cedeerwe** [JuliaMatrices/MatrixDepot.jl#7]
Hi!

It would be very nice to have access also to "training" matricies for Machine Learning, where we have an additional vector containing data. For example the data available on http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/ is widely used and there is no convenient way for loading them at this point. It would be very nice to have that kid of feature!

Cheers,
Dominik

**Comment by weijianzhang** [comment]
Hi Dominik,

Thanks for the message.  I think Machine Learning related dataset is addressed by RDatasets.jl (https://github.com/johnmyleswhite/RDatasets.jl). Please have a check of the package. Is this what you are looking for?

Best,
Weijian

**Comment by cedeerwe** [comment]
Hi Weijian,

you're right, RDatasets.jl includes a lot of important Machine Learning datasets. On the other hand, it doesn't include the datasets on this popular link http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/. It would be nice to have everything "under one roof". But of course, that's a lot of work and I believe you have better work to do :)

Cheers.
Dominik

**Comment by weijianzhang** [comment]
Hi Dominik,

I don't think I will include this Machine Learning datasets in the short term. But I will let you know if I include any Machine Learning related test matrices.

Best wishes,
Weijian
