### ISSUE TITLE
Request: Hansen's test matrices for regularization methods

### ISSUE THREAD

**Issue by jiahao** [JuliaMatrices/MatrixDepot.jl#8]
You might be interested in implementing some matrices in Per-Christian Hansen's paper (see Reference). In that paper, Hansen describes the generation of oscillatory matrices, which are matrices A with some powers A<sup>p</sup> that are totally positive.

The paper also describes other test matrices available in Matlab's Regularization Toolbox.

These matrices would have been nice to have back when JuliaLang/julia#8859 was being discussed. It might still be useful for other purposes.

Reference: [doi:10.1137/0916032](http://dx.doi.org/10.1137/0916032)

**Comment by weijianzhang** [comment]
Thanks a lot for the reference @jiahao, I will look into it.

**Comment by weijianzhang** [comment]
The oscillating matrix ``oscillate`` is now implemented in Matrix Depot.
I also implemented some test problems for regularization methods from the paper:
* ``deriv2``
* ``foxgood``
* ``shaw``
* ``wing``

See http://matrixdepotjl.readthedocs.org/en/latest/regu.html
